project:
  type: website
  output-dir: docs
  
website:
  title: "Ashley Ibarra"
  navbar:
    left:
      - resume.qmd
      - projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

